# Generated by Django 3.2.7 on 2021-10-05 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_rename_articleimage_article_article_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_image',
        ),
    ]
